version: "3.8"

volumes:
  mysql80:
    name: mysql80
  mysql80conf:
    name: mysql80conf # docker run -it -v mysql80conf:/app --rm busybox

services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: condominium
    volumes:
      - mysql80:/var/lib/mysql
      - mysql80conf:/etc/mysql/conf.d

  # GUI: http://localhost:8025
  #mail:
  #  image: mailhog/mailhog:latest
  #  ports:
  #    - 1025:1025
  #    - 8025:8025

