export default {
  data:[
    {
      "id":1,
      "title":"Registrar",
      "menu_id":0,
      "path":"#",
      "icon":"printer",
      "sort":1,
      "children_menus": [
       {
          "id":14,
          "title":"Carrito",
          "menu_id":1,
          "path":"shopcart",
          "sort":5,
          "children_menus":[]
        },{
          "id":4,
          "title":"Usuario",
          "menu_id":1,
          "path":"users.index",
          "sort":1,
          "children_menus":[]
        },{
          "id":5,
          "title":"Clientes",
          "menu_id":1,
          "path":"clients.index",
          "sort":2,
          "children_menus":[]
        },{
          "id":6,
          "title":"Art\u00edculos",
          "menu_id":1,
          "path":"articles",
          "sort":3,
          "children_menus":[]
        },{
          "id":7,
          "title":"Reposici\u00f3nes",
          "menu_id":1,
          "path":"replacements.index",
          "sort":4,
          "children_menus":[]
        }
      ]
   },{
      "id":2,
      "title":"Consultar",
      "menu_id":0,
      "path":"#",
      "icon":"users",
      "sort":2,
      "children_menus":[
        {
          "id":13,
          "title":"Dashboard",
          "menu_id":2,
          "path":"dashboard",
          "sort":4,
          "children_menus":[]
        },{
          "id":8,
          "title":"Ventas",
          "menu_id":2,
          "path":"dashboard",
          "sort":1,
          "children_menus":[]
        },{
          "id":9,
          "title":"Movimientos",
          "menu_id":2,
          "path":"posts.index",
          "sort":2,
          "children_menus":[]
        },{
          "id":10,
          "title":"Existencias",
          "menu_id":2,
          "path":"posts.index",
          "sort":3,
          "children_menus":[]
        }
      ]
    },{
      "id":3,
      "title":"Desarrollo",
      "menu_id":0,
      "path":"#",
      "icon":"office",
      "sort":3,
      "children_menus":[
        {
          "id":11,
          "title":"Men\u00fas",
          "menu_id":3,
          "path":"posts.index",
          "sort":1,
          "children_menus":[]
        },{
          "id":12,
          "title":
          "Roles",
          "menu_id":3,
          "path":"posts.index",
          "sort":2,
          "children_menus":[]
        }
      ]
    }
  ]
 
}
